name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: mohamed2048-apk
          path: bin/*.apk
